from enum import IntEnum


class ResponseCode(IntEnum):
    SUCCESS = 0
    ERROR = -1
    DB_QUERY_ERROR = 1
    ERC20_ALREADY_EXIST = 2
    ERC20_DOES_NOT_EXIST = 3
    ACCOUNT_ID_NOT_FOUND = 4
    ZILA_HANDLE_EXIST = 5
    ACCOUNT_ALREADY_EXIST = 6
    ACCOUNT_DOESNOT_EXIST = 7
    POST_DOESNOT_EXIST = 8
    BOTH_ACCOUNT_AND_FOLLOWER_SHOULD_EXIST = 9
    INVALID_BLOCKCHAIN = 9
    INVALID_AUTHENTICATION = 10
    MISSING_TOKEN = 11
    EMAIL_EXIST = 12
    NOT_REGISTER = 13
